services:
  # FastAPI Backend Service
  - type: web
    name: resume-extractor-api
    env: python
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')" || echo "NLTK download failed"
    startCommand: gunicorn app:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 300
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
    healthCheckPath: /